### ISSUE TITLE
fit_model.exe error

### ISSUE THREAD

**Issue by yfji** [LansburyCH/eos-expression-aware-proxy#1]
Windows. Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9

**Comment by LansburyCH** [comment]
Which version of eos-py are you using? Have you tried pip install --force-reinstall eos-py==0.16.1?
BTW, sorry for the late response. I was busy working on another project.

**Comment by LansburyCH** [comment]
BTW, sorry for the late response. I was busy working on another project.

**Comment by yfji** [comment]
Thanks you, it's the version of eos that caused the problem~
